### ISSUE TITLE
KPB Projects List

### ISSUE THREAD

**Issue by slmclane** [slmclane/PEG#1]
### Budgy
- [ ] [Export Journal Entries to CitySuite](https://github.com/KPB-US/budgy/issues/100)

###  Papyrus
- [ ] Add URL field for youtube video links
- [ ] Clean up user permissions to use groups

###  Joomla
- [ ] Finish PHP Training Course
- [ ] Fix Papyrus List Component on Joomla 4                
- [ ] Fix template/accordion menus for Joomla 4
- [ ] [Continue testing Joomla 4](https://github.com/KPB-US/joomla-www.kpb.us/issues/6)

###  Badger
- [ ] [Configure new badge printer](https://github.com/KPB-US/badgeulator/issues/105)
- [ ] Implement new badge design

###  Database Migrations
- [ ] [Migrate CM databases to admsql5](https://github.com/KPB-US/Content-Manager/issues/2)
- [x] [Move AppealTracking databases to ADMSQL5](https://github.com/KPB-US/AppealsTracking1/issues/8)
- [ ] [Move NPRSA_SPORTSQL databases to ADMSQL5](https://github.com/KPB-US/NPRSA_Sportsman/issues/1)

###  MyKPB
- [ ] [Add collapsible elements (comments, user permissions for form statuses)](https://github.com/KPB-US/my-kpb-us/issues/395)
- [ ] Create MyKPB admin usage guide
- [ ] [Bulk-Mail when new ABA forms are published](https://github.com/KPB-US/my-kpb-us/issues/567)

###  Timesheets
- [ ] [NPRSA Timesheets auto-import](https://github.com/KPB-US/timesheets/issues/299)

###  Sharepoint
- [ ] [MJ Licenses - Allow reviewers to mark licenses as protested](https://github.com/KPB-US/Sharepoint/issues/16)
- [ ] River Center – Material Sites

###  Addressing Assistant
- [ ] [Fix office integration so letters can be generated (or design a workaround)](https://github.com/KPB-US/AddressingAssistant2/issues/1) 

###  Application Maintenance
- [ ] Update Debian on Servers
- [ ] Update Ruby on Applications
- [ ] Update Harepoint
- [ ] Write Instructions for each update process
